In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
data_set = pd.read_csv(r"C:\Users\DELL\Downloads\archive (3).zip")
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [5]:
print(X)

[[2 1 1 ... 2 2 3]
 [2 1 2 ... 1 2 5]
 [2 1 2 ... 2 2 3]
 ...
 [2 13 2 ... 2 2 7]
 [2 13 2 ... 2 2 7]
 [2 13 2 ... 2 2 7]]


In [6]:
print(y)

[97 97  2 ... 97 97 97]


In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

imputer.fit(X[:, 0:1])
X[: , 0:1] = imputer.transform(X[:, 0:1])

In [8]:
print(X)

[[2.0 1 1 ... 2 2 3]
 [2.0 1 2 ... 1 2 5]
 [2.0 1 2 ... 2 2 3]
 ...
 [2.0 13 2 ... 2 2 7]
 [2.0 13 2 ... 2 2 7]
 [2.0 13 2 ... 2 2 7]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [13]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
print(X)

[[1.0 0.0 0.0 ... 2 2 3]
 [1.0 0.0 0.0 ... 1 2 5]
 [1.0 0.0 0.0 ... 2 2 3]
 ...
 [0.0 0.0 0.0 ... 2 2 7]
 [0.0 0.0 0.0 ... 2 2 7]
 [0.0 0.0 0.0 ... 2 2 7]]


In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [16]:
print(y)

[2 2 1 ... 2 2 2]


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [18]:
print(X_train)

[[0.0 0.0 0.0 ... 2 1 5]
 [0.0 0.0 0.0 ... 2 2 3]
 [0.0 0.0 0.0 ... 2 2 6]
 ...
 [0.0 0.0 0.0 ... 2 1 3]
 [0.0 0.0 0.0 ... 2 2 5]
 [0.0 0.0 0.0 ... 2 2 3]]


In [19]:
print(X_test)

[[0.0 0.0 0.0 ... 2 2 7]
 [0.0 0.0 0.0 ... 2 2 7]
 [0.0 0.0 0.0 ... 2 2 7]
 ...
 [0.0 0.0 0.0 ... 2 1 7]
 [0.0 0.0 0.0 ... 2 2 3]
 [0.0 0.0 0.0 ... 2 2 3]]


In [20]:
print(y_train)

[2 2 2 ... 2 2 2]


In [21]:
print(y_test)

[2 2 2 ... 2 2 2]
